-- 여기는 관리자 화면입니다


CREATE TABLESPACE myIOTs DATAFILE 'D:/bizwork/ordata/myIOTS.dbf'
SIZE 100M AUTOEXTEND ON NEXT 1M;

CREATE USER myioUser IDENTIFIED BY 1234
DEFAULT TABLESPACE myIOTS;

DROP USER myioUser;
GRANT DBA TO myioUser;


